name: "Update semver"
description: "Updates major/minor release tags on a tag push"
author: "Rick Staa"
inputs:
  github_token:
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    default: "${{ github.token }}"
  tag:
    description: "Optional. Existing tag to update from. Default comes from $GITHUB_REF."
    required: false
  message:
    description: "Tag message."
    required: false
  major_version_tag_only:
    description: "Optional. Create only major version tags."
    required: false
  move_patch_tag:
    description: "Optional. Move the patch tag to the latest commit."
    required: false
  gpg_private_key:
    description: "Optional. GPG key to sign the tag with."
    required: false
  gpg_passphrase:
    description: "Optional. GPG key passphrase."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "refresh-cw"
  color: "blue"
